-- 1. Create the Role
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS ROSETTA_ROLE;

-- 2. Create the Warehouse
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS ROSETTA_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Grant usage of the warehouse to the role
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE ROSETTA_WH TO ROLE ROSETTA_ROLE;

USE ROLE ACCOUNTADMIN;
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- Create Database
CREATE DATABASE IF NOT EXISTS DEVELOPMENT;

-- CREATE SCHEMA
USE DATABASE DEVELOPMENT;
CREATE SCHEMA IF NOT EXISTS ETL_SCHEMA;
CREATE SCHEMA IF NOT EXISTS BRONZE;

----------------------------------------------------------------------
-- 3. Grants for First Path: DATABASE DEVELOPMENT / SCHEMA ETL_SCHEMA
----------------------------------------------------------------------
-- Grant Usage on Database
GRANT USAGE ON DATABASE DEVELOPMENT TO ROLE ROSETTA_ROLE;

-- Grant Usage on Schema
GRANT USAGE ON SCHEMA DEVELOPMENT.ETL_SCHEMA TO ROLE ROSETTA_ROLE;

-- Specific permissions requested (Create Table, Pipe, Stream, Task)
GRANT CREATE TABLE ON SCHEMA DEVELOPMENT.ETL_SCHEMA TO ROLE ROSETTA_ROLE;
GRANT CREATE PIPE ON SCHEMA DEVELOPMENT.ETL_SCHEMA TO ROLE ROSETTA_ROLE;
GRANT CREATE STREAM ON SCHEMA DEVELOPMENT.ETL_SCHEMA TO ROLE ROSETTA_ROLE;
GRANT CREATE TASK ON SCHEMA DEVELOPMENT.ETL_SCHEMA TO ROLE ROSETTA_ROLE;
GRANT CREATE STAGE ON SCHEMA DEVELOPMENT.ETL_SCHEMA TO ROLE ROSETTA_ROLE; -- Required for Snowpipe

-- Note: To execute/resume tasks, the role needs the account-level privilege
USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE ROSETTA_ROLE;
USE ROLE SECURITYADMIN;

----------------------------------------------------------------------
-- 4. Grants for Second Path: DATABASE DEVELOPMENT / SCHEMA BRONZE
----------------------------------------------------------------------
-- Grant Usage on Database
-- Already granted above for DEVELOPMENT

-- Grant Usage on Schema
GRANT USAGE ON SCHEMA DEVELOPMENT.BRONZE TO ROLE ROSETTA_ROLE;

-- Specific permissions requested
GRANT CREATE TABLE ON SCHEMA DEVELOPMENT.BRONZE TO ROLE ROSETTA_ROLE;
GRANT CREATE PIPE ON SCHEMA DEVELOPMENT.BRONZE TO ROLE ROSETTA_ROLE;
GRANT CREATE STAGE ON SCHEMA DEVELOPMENT.BRONZE TO ROLE ROSETTA_ROLE;

----------------------------------------------------------------------
-- 5. Create the User
----------------------------------------------------------------------
CREATE USER IF NOT EXISTS ROSETTA_USER
    PASSWORD = 'PlaceholderPassword123!' -- Change this immediately
    DEFAULT_ROLE = ROSETTA_ROLE
    DEFAULT_WAREHOUSE = ROSETTA_WH
    COMMENT = 'User for Kafka Connector Service';

-- Grant the Role to the User
GRANT ROLE ROSETTA_ROLE TO USER ROSETTA_USER;

USE ROLE SECURITYADMIN;

ALTER USER ROSETTA_USER SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA35pIXkMgwFjQ50IkQfMeDygKwq88wu7zCuDRnafgRKjeCxNRoW52e59QZKrlT1x3kRZkmRuQTAszdGseq81Mqs5VHs9UDsbaPnt7CRF7+H/JH3jKZA9dPC3KbA/7F2Hfk4YsCHLC6yzmNvABJ+8A1r2/2JdbJF+KjlgMq75/RGCJ2ysfxPWZomhmSYWl68fm8k/URF++ZB2MyJfd1vXQLHnfy0FEdhitrnqgmBfKA1U3TKMo0lixZU5bOhoSPBFpjyZnUaCuojSL/EY2zgDgfUw9wESxzcEV/0QhRt5e2vIZF7KPzQpdjo5ycjml16s6o+ZdBdFFwXqQlP7I8hkU6wIDAQAB';

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE ROSETTA_ROLE;


-- 1. Grant access to the Database and Schema
-- Already granted above for DEVELOPMENT
GRANT USAGE ON SCHEMA DEVELOPMENT.BRONZE TO ROLE ROSETTA_ROLE;

-- 2. Grant permissions on ALL EXISTING tables
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
ON ALL TABLES IN SCHEMA DEVELOPMENT.BRONZE 
TO ROLE ROSETTA_ROLE;

-- 3. Grant permissions on ALL FUTURE tables (automatically applied when created)
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE 
ON FUTURE TABLES IN SCHEMA DEVELOPMENT.BRONZE 
TO ROLE ROSETTA_ROLE;

GRANT USAGE ON DATABASE DEVELOPMENT TO ROLE ROSETTA_ROLE;
GRANT USAGE ON SCHEMA DEVELOPMENT.BRONZE TO ROLE ROSETTA_ROLE;
GRANT CREATE PIPE ON SCHEMA DEVELOPMENT.BRONZE TO ROLE ROSETTA_ROLE;
GRANT USAGE ON WAREHOUSE ROSETTA_WH TO ROLE ROSETTA_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEVELOPMENT.BRONZE TO ROLE ROSETTA_ROLE;
GRANT READ, WRITE ON ALL STAGES IN SCHEMA DEVELOPMENT.BRONZE TO ROLE ROSETTA_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DEVELOPMENT.BRONZE TO ROLE ROSETTA_ROLE;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA DEVELOPMENT.BRONZE TO ROLE ROSETTA_ROLE;